### Ant Colony Optimization - Ant System

In [1]:
import numpy as np
import random


In [2]:
# city distance matrix
d=np.array(
     [[0,10,12,11,14],
      [10,0,13,15,8],
      [12,13,0,9,14],
      [11,15,9,0,16],
      [14,8,14,16,0]])

![](tsp.png)

In [3]:
m_city=len(d)  # number cities

In [4]:
# ACO paramters
alpha=1 # aco parameter
beta=2 # aco parameter
rho=.5 # evaporation rate

In [5]:
#eta - generate transition visibility or desirability - calculated as inverse of distance of d[[]]
v=[ 1/i if i!=0 else 0 for j in d for i in j]
v=np.reshape(v,(5,5))
print(v)

[[0.         0.1        0.08333333 0.09090909 0.07142857]
 [0.1        0.         0.07692308 0.06666667 0.125     ]
 [0.08333333 0.07692308 0.         0.11111111 0.07142857]
 [0.09090909 0.06666667 0.11111111 0.         0.0625    ]
 [0.07142857 0.125      0.07142857 0.0625     0.        ]]


In [ ]:
# Parameters
start_city=4
n_ants=10  #umber of ants
m_city=len(d)
iter=5

f=np.zeros(n_ants)
best_tour=np.zeros((iter,m_city+1))
best_dist=np.zeros(iter)

#random restarts
for it in range(iter):
    #initializations    
    tau=.1*np.ones_like(d)
    f=np.zeros(n_ants)
    ants=np.zeros((n_ants,m_city+1))
    
    ants[:,0]=start_city        # starting city 
    ants[:,m_city]=start_city    # return back to starting city
    
    for i in range(n_ants):     # number of ants
        tv=np.copy(v)
        
        for j in range(m_city): # number of cities
            c=int(ants[i,j])
            #print(c)
            tv[:,c]=0 # make the current city unavailable (as a mask)
            
            #calculate pheromones from city c to other cities
            t=np.power(tau[c],beta)*np.power(tv[c],alpha) 
            sum_t=sum(t)
            
            p=(1/sum_t)*t if sum_t!=0 else 0.0001*t
            #print(j,t)

            #now select the next j+1 city
            s=0
            r= random.random()
            for k in range(m_city): # for number of cities
                s=s+p[k]
                if r<=s:
                    ants[i,j+1]=k
                    break
        
    #calculate tour distance               
    for ii in range(n_ants):
        s=0
        for jj in range(m_city):
            s=s+d[int(ants[ii,jj]),int(ants[ii,jj+1])]
        f[ii]=s
        
    #print(ants)
    #print(f)
    
    minf=np.min(f)
    idx=np.argmin(f)
    
    #All ants update pheromones based on solution found
    tau=tau*(1-rho)
    for i in range(n_ants):
        for j in range(m_city):
            delta=1/f[i] if f[i] !=0 else 0
            tau[int(ants[i,j]),int(ants[i,j+1])]=tau[int(ants[i,j]),int(ants[i,j+1])]+delta
    
    best=np.copy(ants[idx])
    s=0
    for j in range(m_city):
         s=s+d[int(best[j]),int(best[j+1])]
    print(s,best)
    
    #store for each iteration
    best_tour[it]=np.copy(best)
    best_dist[it]=s

#get the iteration best values
iter_idx=np.argmin(best_dist)
print(best_dist)
print(best_tour[iter_idx], best_dist[iter_idx])

[52. 52. 52. 58. 55.]
[4. 1. 0. 3. 2. 4.] 52.0


### Task 1

1. Modify it so that only the best ant modify the pheromone
1. Modify it so that the pheromones evaporate

The above 2 tasks will make it an Ant Colony System. 

### Task 2
1. Test the system with a larger number of cities. 


### Questions
1. If given a solution, can another solution be obtained just be inspection?
1. What if the starting city is different, will the answer be different?